services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - "${PORT:-3000}:3000"
        volumes:
            - .:/app
